services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Services\RemoteMachineRemover:
        public: true

    Symfony\Component\Messenger\Transport\InMemoryTransport:
        alias: 'messenger.transport.async'

    App\Tests\Services\Asserter\MessengerAsserter:
        public: true
        arguments:
            $transport: '@messenger.transport.async'

    GuzzleHttp\Handler\MockHandler:
        public: true
        class: GuzzleHttp\Handler\MockHandler

    GuzzleHttp\HandlerStack:
        class: GuzzleHttp\HandlerStack
        factory: ['GuzzleHttp\HandlerStack', 'create']
        arguments:
            $handler: '@GuzzleHttp\Handler\MockHandler'

    App\Services\RequestIdFactoryInterface:
        class: App\Tests\Services\SequentialRequestIdFactory

    App\Tests\Services\Asserter\MessageStateEntityAsserter:
        public: true

    App\Services\RemoteRequestRetryDecider:
        public: true
        arguments:
            $deciders:
                - '@App\Services\RemoteRequestRetryDecider\DigitalOcean\DigitalOceanRemoteRequestRetryDecider'
