services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Services\RemoteMachineRemover:
        public: true

    Symfony\Component\Messenger\Transport\InMemoryTransport:
        alias: 'messenger.transport.async'

    App\Tests\Services\Asserter\MessengerAsserter:
        public: true
        arguments:
            $transport: '@messenger.transport.async'

    App\Services\RequestIdFactoryInterface:
        class: App\Tests\Services\SequentialRequestIdFactory

    App\Tests\Services\TestMachineRequestFactory:
        public: true

    App\Tests\Proxy\DigitalOceanV2\Api\DropletApiProxy:
        public: true

    DigitalOceanV2\Api\Droplet:
        public: true
        alias: App\Tests\Proxy\DigitalOceanV2\Api\DropletApiProxy
