services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tests\Services\EntityRemover:
        public: true

    Symfony\Component\Messenger\Transport\InMemoryTransport:
        alias: 'messenger.transport.async'

    App\Services\RequestIdFactoryInterface:
        class: App\Tests\Services\SequentialRequestIdFactory

    App\Tests\Services\TestMachineRequestFactory:
        public: true

    DigitalOceanV2\Client:
        class: App\Tests\Proxy\DigitalOceanV2\ClientProxy

    App\Tests\Proxy\DigitalOceanV2\Api\DropletApiProxy:
        public: true
        calls:
            - prepareGetByIdZeroCall: []

    GuzzleHttp\Psr7\HttpFactory:

    Psr\Http\Message\RequestFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\ResponseFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\ServerRequestFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\StreamFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\UploadedFileFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Psr\Http\Message\UriFactoryInterface:
        alias: GuzzleHttp\Psr7\HttpFactory

    Symfony\Bridge\PsrHttpMessage\HttpMessageFactoryInterface:
        class: Symfony\Bridge\PsrHttpMessage\Factory\PsrHttpFactory

    SmartAssert\SymfonyTestClient\SymfonyClient:

    app.tests.integration.http.client:
        public: true
        class: GuzzleHttp\Client
        arguments:
            $config:
                base_uri: "http://localhost:9090/"

    SmartAssert\SymfonyTestClient\HttpClient:
        arguments:
            $httpClient: '@app.tests.integration.http.client'

    app.tests.services.application.client.symfony:
        public: true
        class: App\Tests\Services\ApplicationClient\Client
        arguments:
            $client: '@SmartAssert\SymfonyTestClient\SymfonyClient'
            $healthCheckUrl: '%health_check_bundle_health_check_path%'
            $statusUrl: '%health_check_bundle_status_path%'

    app.tests.services.application.client.http:
        public: true
        class: App\Tests\Services\ApplicationClient\Client
        arguments:
            $client: '@SmartAssert\SymfonyTestClient\HttpClient'
            $healthCheckUrl: '%health_check_bundle_health_check_path%'
            $statusUrl: '%health_check_bundle_status_path%'

    App\Tests\Services\AuthenticationConfiguration:
        public: true
        arguments:
            $userEmail: 'user@example.com'
            $userPassword: 'password'

    App\Tests\Services\Asserter\JsonResponseAsserter:
        public: true

    App\Tests\Services\Asserter\MachineResponseAsserter:
        public: true
