name: Create release

on:
  workflow_dispatch:
    inputs:
      commit_hash:
        description: Commit hash to release from
        required: true
      should_release:
        description: Create release?
        required: true
        default: "true"

jobs:
  create-release:
    name: Create release
    runs-on: ubuntu-latest

    steps:
      - name: Output inputs
        env:
          INPUTS: ${{ toJson(github.events.input) }}
        run: jq '.' <<< "$INPUTS"

      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.commit_hash }}

      - name: Set should_release
        id: should_release
        run: |
          SHOULD_RELEASE="${{ github.event.inputs.should_release }}"

          if [ "$SHOULD_RELEASE" != "true" ]; then
            SHOULD_RELEASE="false"
          fi

          echo "::set-output name=value::$SHOULD_RELEASE"

      - name: Set release tag
        id: release_tag
        run: |
          RELEASE_TAG=$(./ci/scripts/create-version-label.sh)
          TAG_EXISTENCE_COUNT=$(git tag | grep "$RELEASE_TAG" -c)

          if [ "0" != "$TAG_EXISTENCE_COUNT" ]; then
            echo "Generated release tag \"$RELEASE_TAG\" already exists"
            git tag
            exit 1
          fi

          echo "::set-output name=value::$RELEASE_TAG"

      - name: Read worker image
        id: worker_image
        run: |
          WORKER_IMAGE=$(cat ./worker_image)
          if [ "" = "$WORKER_IMAGE" ]; then
            echo "worker_image not set"
            exit 1
          fi

          echo "::set-output name=value::$WORKER_IMAGE"

      - name: Verify setup
        run: |
          echo "commit_hash: ${{ github.event.inputs.commit_hash }}"
          echo "should_release: ${{ steps.should_release.outputs.value }}"
          echo "release_tag: ${{ steps.release_tag.outputs.value }}"
          echo "worker_image: ${{ steps.worker_image.outputs.value }}"

      - name: Create release
        if: ${{ steps.should_release.outputs.value == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN_SELF }}
          TAG: ${{ steps.release_tag.outputs.value }}
          TARGET: ${{ github.event.inputs.commit_hash }}
          TITLE: "Automatic release ${{ steps.release_tag.outputs.value }}"
          NOTES: "Worker image ${{ steps.worker_image.outputs.value }}"
        run: gh release create "$TAG" --target "$TARGET" --title "$TITLE" --notes "$NOTES"
