name: Deploy

on:
  workflow_dispatch:
    inputs:
      worker_manager_version:
        description: Worker manager version
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Dispatch service-configure event to image builder
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.IMAGE_BUILDER_TOKEN }}
          repository: smartassert/image-builder
          event-type: service-configure
          client-payload: |
            {
              "service_id": "worker-manager",
              "build_configuration": "{\"version\": \"${{ github.event.inputs.worker_manager_version }}\"}"
            }

      - name: Dispatch service-configure event to instance manager
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.INSTANCE_MANAGER_TOKEN }}
          repository: smartassert/instance-manager
          event-type: service-configure
          client-payload: |
            {
              "service_id": "worker_manager",
              "state_url": "/",
              "health_check_url": "/health-check"
            }
