name: Release

on:
  push:
    branches:
      - main
  release:
    types:
      - published

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set version
        id: version
        env:
          RELEASE_TAG_NAME: ${{ github.event.release.tag_name }}
        run: |
          [[ -n "$RELEASE_TAG_NAME" ]] && echo "::set-output name=value::$RELEASE_TAG_NAME" || echo "::set-output name=value::master"

      - name: Read worker image
        id: build_config
        run: echo "::set-output name=value::$(cat ./worker_image)"

      - name: Examine build config
        run: |
          echo WORKER_IMAGE ${{ steps.build_config.outputs.value }}
          echo VERSION ${{ steps.version.outputs.value }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Repository
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/smartassert/worker-manager:${{ steps.version.outputs.value }}
          build-args: |
            VERSION=${{ steps.version.outputs.value }}
            WORKER_IMAGE=${{ steps.build_config.outputs.value }}

      - name: Trigger deploy workflow
        if: ${{ github.event_name == 'release' }}
        uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: Deploy
          token: ${{ secrets.PAT_TOKEN_SELF }}
          inputs: |
            {
              "worker_manager_version": "${{ steps.version.outputs.value }}"
            }
