name: Store build config

on:
  repository_dispatch:
    types: [worker-deploy]
  workflow_dispatch:
    inputs:
      worker_image:
        description: Worker image ID
        required: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      worker_image: ${{ steps.worker_image.outputs.value }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN_SELF }}

      - name: Checkout bash-ga-ci-tools
        uses: actions/checkout@v2
        with:
          repository: smartassert/bash-ga-ci-tools
          path: ./vendor/smartassert/bash-ga-ci-tools
          ref: main

      - name: Set worker image version
        id: worker_image
        env:
          VALUE1: ${{ github.event.client_payload.worker_image }}
          VALUE2: ${{ github.event.inputs.worker_image }}
        run: echo "::set-output name=value::$(./vendor/smartassert/bash-ga-ci-tools/src/select-exclusive-value-from-two-values.sh)"

  verify-setup:
    name: Verify setup
    runs-on: ubuntu-latest
    needs: setup

    steps:
      - name: Checkout bash-ga-ci-tools
        uses: actions/checkout@v2
        with:
          repository: smartassert/bash-ga-ci-tools
          path: ./vendor/smartassert/bash-ga-ci-tools
          ref: main

      - name: Output
        env:
          OUTPUTS: ${{ toJson(needs.setup.outputs) }}
        run: |
          echo "$OUTPUTS"
          ./vendor/smartassert/bash-ga-ci-tools/src/json-contains-no-empty-values.sh

  update-build-configuration:
    name: Update build configuration
    runs-on: ubuntu-latest
    needs: [setup, verify-setup]
    outputs:
      create-release: ${{ steps.commit.outputs.changes_detected }}
      commit-hash: ${{ steps.commit.outputs.commit_hash }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN_SELF }}

      - name: Update
        env:
          WORKER_IMAGE: ${{ needs.setup.outputs.worker_image }}
        run: echo -n "$WORKER_IMAGE" > ./worker_image

      - name: Commit
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatic worker image update: ${{ needs.setup.outputs.worker_image }}"

  trigger-create-release:
    name: Trigger create release workflow
    runs-on: ubuntu-latest
    needs: [setup, update-build-configuration]
    if: ${{ needs.update-build-configuration.outputs.create-release == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN_SELF }}

      - name: Trigger workflow
        if: ${{ github.event_name == 'release' }}
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN_SELF }}
        run:
          gh workflow run create-release.yml \
          -f commit_hash="${{ needs.update-build-configuration.outputs.commit-hash }}" \
          -f should_release="true"
