name: Store build config

on:
  repository_dispatch:
    types: [worker-deploy]

jobs:
  build:
    name: Store build config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN_SELF }}

      - name: Set version
        id: version
        run: echo "::set-output name=value::$(./ci/scripts/create-version-label.sh)"

      - name: Update build.env
        id: update
        env:
          WORKER_IMAGE: ${{ github.event.client_payload.worker_image }}
        run: echo "WORKER_IMAGE=$WORKER_IMAGE" > build.env

      - name: Commit changes
        id: auto-commit-action
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatic build.env for worker image ${{ github.event.client_payload.worker_image }}"

      - name: Get latest commit hash
        id: commit_hash
        if: ${{ steps.auto-commit-action.outputs.changes_detected == 'true' }}
        run: echo "::set-output name=value::$(git rev-parse HEAD)"

      - name: Create release
        if: ${{ steps.auto-commit-action.outputs.changes_detected == 'true' }}
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN_SELF }}
          TAG: ${{ steps.version.outputs.value }}
          TARGET: ${{ steps.commit_hash.outputs.value }}
          TITLE: "Automatic release ${{ steps.version.outputs.value }}"
          NOTES: "Worker image ${{ github.event.client_payload.worker_image }}"
        run: gh release create "$TAG" --target "$TARGET" --title "$TITLE" --notes "$NOTES"
