name: store-worker-image

on:
  repository_dispatch:
    types: [worker-deploy]
  workflow_dispatch:
    inputs:
      worker_image:
        description: Worker image ID
        required: true

jobs:
  store-build-config:
    name: Store build config
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_TOKEN_SELF }}

      - name: Set env.worker_image
        env:
          REPOSITORY_DISPATCH_VALUE: ${{ github.event.client_payload.worker_image }}
          WORKFLOW_DISPATCH_VALUE: ${{ github.event.inputs.worker_image }}
        run: |
          WORKER_IMAGE="${REPOSITORY_DISPATCH_VALUE:-$WORKFLOW_DISPATCH_VALUE}"
          if [ "" = "$WORKER_IMAGE" ]; then
            echo "worker_image not set"
            exit 1
          fi

          echo -n "$WORKER_IMAGE" > ./worker_image
          echo "worker_image=$WORKER_IMAGE" >> "$GITHUB_ENV"

      - name: Commit
        id: commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Automatic worker image update: ${{ env.worker_image }}"

      - name: Trigger workflow
        if: ${{ steps.commit.outputs.changes_detected == 'true' }}
        env:
          GH_TOKEN: ${{ secrets.PAT_TOKEN_SELF }}
        run: |
          gh workflow run create-release.yml \
          -f commit_hash="${{ steps.commit.outputs.commit_hash }}" \
          -f should_release="true"
