name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration:
    name: PHP ${{ matrix.php }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.1']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          args: --ignore-platform-reqs --quiet

      - name: Pull images
        run: composer integration-pull

      - name: Docker layer caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Setup integration environment
        env:
          PRIMARY_DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN_TEST }}
          SECONDARY_DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN_TEST }}
          VERSION: gh-action-version
        run: |
          VERSION=$VERSION composer integration-setup
          docker-compose -f tests/build/docker-compose.yml exec -T app touch /app/var/log/messenger.prod.log
          sleep 10

      - name: Test status, machine creation, health check
        env:
          PRIMARY_DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN_TEST }}
          SECONDARY_DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN_TEST }}
          EXPECTED_VERSION: gh-action-version
        run: composer test-integration

      - name: "Debug: output messenger log ..."
        if: ${{ always() }}
        run: docker-compose -f tests/build/docker-compose.yml exec -T app cat /app/var/log/messenger.prod.log
