name: Unit and Functional Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit:
    name: Unit - PHP ${{ matrix.php }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.0']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          args: --ignore-platform-reqs --quiet

      - name: Run PHPUnit unit tests
        run: composer test-unit

  functional:
    name: Functional - PHP ${{ matrix.php }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.0']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php }}
          args: --ignore-platform-reqs --quiet

      - name: Create DB schema
        run: composer db-setup

      - name: Run tests
        run: composer test-functional
