name: Integration Tests (Application)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration:
    name: PHP ${{ matrix.php }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.3']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install composer dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Pull images
        run: composer integration-pull

      - name: Docker layer caching
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Setup integration environment
        env:
          PRIMARY_DIGITALOCEAN_API_TOKEN: primary_digitalocean_api_token
          SECONDARY_DIGITALOCEAN_API_TOKEN: secondary_digitalocean_api_token
          VERSION: gh-action-version
        run: |
          VERSION=$VERSION composer integration-setup
          docker compose -f tests/build/docker-compose.yml exec -T app touch /app/var/log/messenger.prod.log
          sleep 10

      - name: Run tests
        env:
          EXPECTED_VERSION: gh-action-version
        run: composer test-integration-application
