name: Integration Tests - Health Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  integration:
    name: Health check - PHP ${{ matrix.php-versions }} ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php-versions: ['8.0']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: pgsql

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-versions }}
          args: --ignore-platform-reqs --quiet

      - name: Pull images
        run: composer integration-pull

      - name: Docker layer caching
        uses: satackey/action-docker-layer-caching@v0.0.11

      - name: Setup integration environment
        env:
          DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN_TEST }}
        run: |
          composer integration-setup
          sleep 10

      - name: Run asynchronous tests
        env:
          DIGITALOCEAN_API_TOKEN: ${{ secrets.DIGITALOCEAN_API_TOKEN_TEST }}
        run: |
          composer test-integration-health-check
