name: Integration Tests (Foo)

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  integration:
    name: PHP ${{ matrix.php }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.3']
    runs-on: ${{ matrix.operating-system }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Install composer dependencies
        run: |
          composer config github-oauth.github.com "$GITHUB_TOKEN"
          composer install --no-progress --prefer-dist --optimize-autoloader
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup integration environment
        env:
          PRIMARY_DIGITALOCEAN_API_TOKEN: invalid_primary_digitalocean_api_token
          SECONDARY_DIGITALOCEAN_API_TOKEN: invalid_secondary_digitalocean_api_token
        run: |
          VERSION=$VERSION composer integration-setup
          docker compose -f tests/build/docker-compose.yml exec -T app touch /app/var/log/messenger.prod.log
          sleep 10

      - name: Run tests
        env:
          PRIMARY_DIGITALOCEAN_API_TOKEN: invalid_primary_digitalocean_api_token
          SECONDARY_DIGITALOCEAN_API_TOKEN: invalid_secondary_digitalocean_api_token
        run: composer test-integration-foo
